/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.example.animations.animationsactivities

import com.example.animations.animationsactivities.BaseAnimationActivity


//Good than LaunchAndSpinAnimatorSetAnimationActivity(i.e. set of multiple animations)  in terms of performance

class LaunchAndSpinViewPropertyAnimatorAnimationActivity : BaseAnimationActivity() {

    /*override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }*/

    override fun onStartAnimation() {
        rocket.animate()
                .translationY(-screenHeight)
                .rotationBy(360f)
                .setDuration(BaseAnimationActivity.Companion.DEFAULT_ANIMATION_DURATION)
                .start()
    }
}
